<?php
defined('BASEPATH') or exit('No direct script access allowed');

class ProjectToOverleaf extends CI_Controller
{

	function __construct()
	{
		parent::__construct();
		if (!$this->session->userdata('logged_in')) {
			redirect(base_url());
		}

		// $this->load->helper('url', 'english');

		$this->lang->load('btn', 'english');
		// $this->lang->load('btn','portuguese-brazilian');
		$this->lang->load('overleaf', 'english');
		// $this->lang->load('quality_mp','portuguese-brazilian');

		$this->load->model('view_model');
		$this->load->model('Project_model');
		$this->load->model('log_model');
		$this->load->helper('url');
		$this->load->model('Project_to_overleaf_model');
		$this->load->helper('log_activity');

		// Integration
		$this->load->model('Admin_model');
		$this->load->model('Project_Charter_model');
		$this->load->model('Project_management_model');
		$this->load->model('Project_performance_report_model');
		$this->load->model('Change_request_model');
		$this->load->model('Project_Closure_model');
		$this->load->model('Business_case_model');
		$this->load->model('Delivery_acceptance_term_model');
		$this->load->model('Change_log_model');
		$this->load->model('Final_report_model');
		$this->load->model('Benefits_plan_model');
		$this->load->model('Work_performance_report_model');
		$this->load->model('Issues_record_model');
		$this->load->model('Lesson_learned_register_model');

		//
	}
	public function integrationToOverleaf($project_id)
	{
		$file = "";
		$file .= "\chapter{Project Integration Management}\n";

		$dataBusinessCase = $this->Business_case_model->get($project_id);

		$file .= "\section{Business Case}\n";
		$file .= "\subsection{Business Deals}\n";
		$file .= $dataBusinessCase[0]->business_deals . "\n";

		$file .= "\subsection{Situation Analysis}\n";
		$file .= $dataBusinessCase[0]->situation_analysis . "\n";

		$file .= "\subsection{Recommendation}\n";
		$file .= $dataBusinessCase[0]->recommendation . "\n";

		$file .= "\subsection{Evaluation}\n";
		$file .= $dataBusinessCase[0]->evaluation . "\n";
	}

	public function exportLatex($project_id)
	{
		$steps = $this->input->post('step');
		// $project_id = $this->input->post('project_id');

		$this->db->where('user_id',  $_SESSION['user_id']);
		$this->db->where('project_id',  $project_id);
		$project['dados'] = $this->db->get('project_user')->result();

		// $listUsers = $this->Admin_model->get_user_list


		// $user_email = "thiago@hotmail.com";




		$this->load->view('frame/header_view');
		$this->load->view('frame/topbar');
		$this->load->view('frame/sidebar_nav_view');
		$this->load->view('project/project_to_overleaf');







		$project = $this->Project_to_overleaf_model->get_project_export_latex($project_id);
		$file = "";

		//Configuring File Latex
		$file .= "\documentclass[twoside,a4paper,11pt]{book}\n";
		$file .= "\usepackage[utf8]{inputenc}\n";
		$file .= "\usepackage{titlesec}\n";
		$file .= "\usepackage{graphicx}\n";
		$file .= "\usepackage{booktabs}\n";
		$file .= "\usepackage{float}\n";
		$file .= "\usepackage[alf]{abntex2cite}\n";
		$file .= "\usepackage[brazilian,hyperpageref]{backref}\n";


		$file .= "\\renewcommand{\backrefpagesname}{Citado na(s) página(s):~}\n";
		$file .= "\\renewcommand{\backref}{}\n";
		$file .= "\\renewcommand*{\backrefalt}[4]{\n";
		$file .= "\ifcase #1 %\n";
		$file .= "Nenhuma citação no texto.%\n";
		$file .= "\or\n";
		$file .= "Citado na página #2.%\n";
		$file .= "\\else\n";
		$file .= "Citado #1 vezes nas páginas #2.%\n";
		$file .= "\\fi}%\n";
		$file .= "\n";

		//Title
		$data['title'] = $this->Project_model->getProjectName($project_id);
		$file .= "\\title {" . $data['title'] . "}\n";

		// Authors
		$file .= "\author{Lucas Abner}\n";

		$file .= "hspace{.45\textwidth}\n";
		$file .= "Generated By: Silver Bullet 2021\n";
		$file .= "end{minipage}\n";


		// Document
		$file .= "\begin{document}\n";
		$file .= "maketitle\n";

		$file .= "\\tableofcontents\n";
		$file .= "\listoffigures\n";
		$file .= "\listoftables\n";




		foreach ($steps as $step) {
			switch ($step) {
		 		case "Planning":
		 			$this->integrationToOverleaf($project_id);
			}
		 }

		$file .= "\chapter{Project Integration Management}\n";

		$dataBc = $this->Business_case_model->get($project_id);

		


		$file .= "\section{Business Case}\n";
		$file .= "\subsection{Business Deals}\n";
		// var_dump($dataBc);exit;
		$file .= $dataBc[0]->business_deals . "\n";

		$file .= "\subsection{Situation Analysis}\n";
		$file .= $dataBc[0]->situation_analysis . "\n";

		$file .= "\subsection{Recommendation}\n";
		$file .= $dataBc[0]->recommendation . "\n";

		$file .= "\subsection{Evaluation}\n";
		$file .= $dataBc[0]->evaluation . "\n";





		// End Document
		$file .= "\\bibliography{Bib}\n";
		$file .= "\\end{document}\n";

		echo $file;
	}
}
