-- MySQL Script generated by MySQL Workbench
-- Wed Jul 18 15:44:07 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema pmst
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `pmst` ;

-- -----------------------------------------------------
-- Schema pmst
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pmst` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `pmst` ;

-- -----------------------------------------------------
-- Table `project`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `project` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `project` (
  `project_id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NULL,
  `description` VARCHAR(255) NULL,
  `status` BIT(1) NULL,
  PRIMARY KEY (`project_id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `project_charter`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `project_charter` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `project_charter` (
  `project_charter_id` INT NOT NULL AUTO_INCREMENT,
  `scope` VARCHAR(255) NULL,
  `objective` VARCHAR(255) NULL,
  `sucess` VARCHAR(255) NULL,
  `requirements` VARCHAR(255) NULL,
  `assumptions` VARCHAR(255) NULL,
  `constraints` VARCHAR(255) NULL COMMENT 'CREATE TABLE IF NOT EXISTS `mydb`.`projectcharter` (\n  `charter_id` INT NOT NULL AUTO_INCREMENT,\n  `projectcharter_scope` LONGTEXT NULL,\n  `projectcharter_objective` LONGTEXT NULL,\n  `projectcharter_sucess` LONGTEXT NULL,\n  `projectcharter_requirements` LONGTEXT NULL,\n  `projectcharter_assumptions` LONGTEXT NULL,\n  `projectcharter_constraints` LONGTEXT NOT NULL,\n  `projectcharter_risks` LONGTEXT NULL,\n  `projectcharter_milestone` LONGTEXT NULL,\n  PRIMARY KEY (`charter_id`))\nENGINE = InnoDB',
  `risks` VARCHAR(255) NULL,
  `milestone` VARCHAR(255) NULL,
  `budge` VARCHAR(255) NULL,
  `stakeholder` VARCHAR(255) NULL,
  `aprovalReq` VARCHAR(255) NULL,
  `start_date` DATE NULL,
  `end_date` DATE NULL,
  `project_id` INT NOT NULL,
  `status` BIT(1) NULL,
  PRIMARY KEY (`project_charter_id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `stakelholder`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `stakelholder` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `stakelholder` (
  `stakelholder_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL,
  `roles_responsabilies` VARCHAR(255) NULL,
  `status` BIT(1) NULL,
  PRIMARY KEY (`stakelholder_id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `stakeholder_mp`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `stakeholder_mp` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `stakeholder_mp` (
  `stakeholder_mp_id` INT NOT NULL,
  `stakelholder_id` INT NOT NULL,
  `interest` INT NULL,
  `power` INT NULL,
  `influence` INT NULL,
  `impact` INT NULL,
  `average` INT NULL,
  `expectedengagement` VARCHAR(255) NULL,
  `currentengagement` VARCHAR(255) NULL,
  `strategy` VARCHAR(255) NULL,
  `scope` VARCHAR(255) NULL,
  `observation` VARCHAR(255) NULL,
  `project_id` INT NOT NULL,
  `status` BIT(1) NULL,
  PRIMARY KEY (`stakeholder_mp_id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `project_charter_stakelholder`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `project_charter_stakelholder` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `project_charter_stakelholder` (
  `stakelholder_id` INT NOT NULL,
  `project_charter_id` INT NOT NULL,
  `stauts` BIT(1) NULL,
  PRIMARY KEY (`project_charter_id`, `stakelholder_id`))
ENGINE = InnoDB;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
