-- MySQL Script generated by MySQL Workbench
-- Tue Aug 14 14:22:27 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema pmst
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `pmst` ;

-- -----------------------------------------------------
-- Schema pmst
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pmst` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `pmst` ;

--
-- Estrutura da tabela `communication_mp`
--

CREATE TABLE `communication_mp` (
  `communication_id` int(11) NOT NULL,
  `type` varchar(45) DEFAULT NULL,
  `description` varchar(45) DEFAULT NULL,
  `content` varchar(255) DEFAULT NULL,
  `distribution_reason` varchar(255) DEFAULT NULL,
  `language` varchar(45) DEFAULT NULL,
  `channel` varchar(45) DEFAULT NULL,
  `documento_format` varchar(45) DEFAULT NULL,
  `metod` varchar(45) DEFAULT NULL,
  `frequency` varchar(45) DEFAULT NULL,
  `allocated_resources` varchar(45) DEFAULT NULL,
  `format` varchar(45) DEFAULT NULL,
  `local` varchar(45) DEFAULT NULL,
  `project_id` int(11) NOT NULL,
  `status` bit(1) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- --------------------------------------------------------

--
-- Estrutura da tabela `cost_mp`
--

CREATE TABLE `cost_mp` (
  `cost_mp_id` int(11) NOT NULL,
  `project_costs_m` varchar(255) DEFAULT NULL,
  `accuracy_level` text,
  `organizational_procedures` varchar(255) DEFAULT NULL,
  `measurement_rules` text,
  `format_report` varchar(255) DEFAULT NULL,
  `project_id` int(11) NOT NULL,
  `status` bit(1) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- --------------------------------------------------------

--
-- Estrutura da tabela `human_resources_mp`
--

CREATE TABLE `human_resources_mp` (
  `human_resources_mp_id` int(11) NOT NULL,
  `roles_responsibilities` text,
  `organizational_chart` varchar(255) DEFAULT NULL,
  `staff_mp` text,
  `project_id` int(11) NOT NULL,
  `status` bit(1) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- --------------------------------------------------------

--
-- Estrutura da tabela `procurement_mp`
--

CREATE TABLE `procurement_mp` (
  `procurement_mp_id` int(11) NOT NULL,
  `products_services_obtained` text,
  `team_actions` text,
  `performance_metrics` text,
  `project_id` int(11) NOT NULL,
  `status` bit(1) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- --------------------------------------------------------

--
-- Estrutura da tabela `project`
--

CREATE TABLE `project` (
  `project_id` int(11) NOT NULL,
  `title` varchar(255) NOT NULL,
  `description` varchar(255) DEFAULT NULL,
  `objectives` varchar(255) DEFAULT NULL,
  `created_by` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- --------------------------------------------------------

--
-- Estrutura da tabela `project_charter`
--

CREATE TABLE `project_charter` (
  `project_charter_id` int(11) NOT NULL,
  `project_description` text,
  `project_purpose` text,
  `project_objective` text,
  `benefits` text,
  `high_level_requirements` text,
  `initial_assumptions` text,
  `initial_restrictions` text,
  `project_limits` text,
  `high_level_risks` text,
  `summary_schedule` text,
  `budge_summary` text,
  `project_approval_requirements` text,
  `start_date` date DEFAULT NULL,
  `end_date` date DEFAULT NULL,
  `project_id` int(11) NOT NULL,
  `status` bit(1) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- --------------------------------------------------------

--
-- Estrutura da tabela `project_charter_stakeholder`
--

CREATE TABLE `project_charter_stakeholder` (
  `stakeholder_id` int(11) NOT NULL,
  `project_charter_id` int(11) NOT NULL,
  `status` bit(1) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- --------------------------------------------------------

--
-- Estrutura da tabela `project_mp`
--

CREATE TABLE `project_mp` (
  `project_mp_id` int(11) NOT NULL,
  `project_lifecycle` text,
  `project_guidelines` text,
  `change_mp` text,
  `configuration_mp` text,
  `baseline_maintenance` text,
  `stakeholders_communication` text,
  `key_review` text,
  `project_id` int(11) NOT NULL,
  `status` bit(1) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- --------------------------------------------------------

--
-- Estrutura da tabela `project_user`
--

CREATE TABLE `project_user` (
  `project_id` int(11) NOT NULL,
  `user_id` int(11) NOT NULL,
  `access_level` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- --------------------------------------------------------

--
-- Estrutura da tabela `quality_mp`
--

CREATE TABLE `quality_mp` (
  `quality_mp_id` int(11) NOT NULL,
  `methodology` text,
  `related_processes` varchar(255) DEFAULT NULL,
  `expectations_tolerances` text,
  `traceability` text,
  `project_id` int(11) NOT NULL,
  `status` bit(1) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- --------------------------------------------------------

--
-- Estrutura da tabela `requirements_mp`
--

CREATE TABLE `requirements_mp` (
  `requirements_mp_id` int(11) NOT NULL,
  `requirements_collection_proc` text,
  `requirements_prioritization` text,
  `product_metrics` text,
  `project_id` int(11) NOT NULL,
  `status` bit(1) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- --------------------------------------------------------

--
-- Estrutura da tabela `risk_mp`
--

CREATE TABLE `risk_mp` (
  `risk_mp_id` int(11) NOT NULL,
  `methodology` text,
  `roles_responsibilities` text,
  `risk_management_processes` varchar(255) DEFAULT NULL,
  `risks_categories` varchar(255) DEFAULT NULL,
  `risks_probability_impact` varchar(255) DEFAULT NULL,
  `probability_impact_matrix` varchar(255) DEFAULT NULL,
  `reviewed_tolerances` text,
  `traceability` varchar(255) DEFAULT NULL,
  `project_id` int(11) NOT NULL,
  `status` bit(1) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- --------------------------------------------------------

--
-- Estrutura da tabela `schedule_mp`
--

CREATE TABLE `schedule_mp` (
  `schedule_mp_id` int(11) NOT NULL,
  `schedule_model` varchar(255) DEFAULT NULL,
  `accuracy_level` varchar(255) DEFAULT NULL,
  `organizational_procedures` varchar(255) DEFAULT NULL,
  `schedule_maintenance` varchar(255) DEFAULT NULL,
  `performance_measurement` text,
  `report_format` varchar(255) DEFAULT NULL,
  `project_id` int(11) NOT NULL,
  `status` bit(1) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- --------------------------------------------------------

--
-- Estrutura da tabela `scope_mp`
--

CREATE TABLE `scope_mp` (
  `scope_mp_id` int(11) NOT NULL,
  `scope_specification` text,
  `eap_process` text,
  `deliveries_acceptance` text,
  `scope_change_mp` text,
  `project_id` int(11) NOT NULL,
  `status` bit(1) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- --------------------------------------------------------

--
-- Estrutura da tabela `stakeholder_mp`
--

CREATE TABLE `stakeholder_mp` (
  `stakeholder_mp_id` int(11) NOT NULL,
  `stakeholder_id` int(11) NOT NULL,
  `interest` int(11) DEFAULT NULL,
  `power` int(11) DEFAULT NULL,
  `influence` int(11) DEFAULT NULL,
  `impact` int(11) DEFAULT NULL,
  `average` int(11) DEFAULT NULL,
  `expected_engagement` varchar(45) DEFAULT NULL,
  `current_engagement` varchar(45) DEFAULT NULL,
  `strategy` text,
  `scope` text,
  `observation` text,
  `project_id` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- --------------------------------------------------------

--
-- Estrutura da tabela `stakeholder_register`
--

CREATE TABLE `stakeholder_register` (
  `stakeholder_id` int(11) NOT NULL,
  `name` varchar(45) DEFAULT NULL,
  `type` varchar(45) DEFAULT NULL,
  `organization` varchar(45) DEFAULT NULL,
  `position` varchar(45) DEFAULT NULL,
  `role` varchar(45) DEFAULT NULL,
  `responsibility` varchar(45) DEFAULT NULL,
  `email` varchar(45) DEFAULT NULL,
  `phone_number` varchar(45) DEFAULT NULL,
  `work_place` varchar(45) DEFAULT NULL,
  `essential_requirements` text,
  `main_expectations` text,
  `interest_phase` text,
  `observations` text
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- --------------------------------------------------------

--
-- Estrutura da tabela `user`
--

CREATE TABLE `user` (
  `user_id` int(11) NOT NULL,
  `email` varchar(255) NOT NULL,
  `password` varchar(255) NOT NULL,
  `name` varchar(50) NOT NULL,
  `role` varchar(50) NOT NULL,
  `status` tinyint(1) NOT NULL DEFAULT '1',
  `institution` varchar(255) DEFAULT NULL,
  `lattes_address` varchar(255) DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Extraindo dados da tabela `user`
--

INSERT INTO `user` (`user_id`, `email`, `password`, `name`, `role`, `status`, `institution`, `lattes_address`, `created_at`, `updated_at`) VALUES
(0, 'testa@pay-mon.com', 'cccae4d9e246b345f5464e4abc142a27', 'teste', 'user', 1, 'teste', NULL, '2018-08-15 05:25:25', '2018-08-15 03:25:25');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `communication_mp`
--
ALTER TABLE `communication_mp`
  ADD PRIMARY KEY (`communication_id`);

--
-- Indexes for table `cost_mp`
--
ALTER TABLE `cost_mp`
  ADD PRIMARY KEY (`cost_mp_id`);

--
-- Indexes for table `human_resources_mp`
--
ALTER TABLE `human_resources_mp`
  ADD PRIMARY KEY (`human_resources_mp_id`);

--
-- Indexes for table `procurement_mp`
--
ALTER TABLE `procurement_mp`
  ADD PRIMARY KEY (`procurement_mp_id`);

--
-- Indexes for table `project`
--
ALTER TABLE `project`
  ADD PRIMARY KEY (`project_id`),
  ADD KEY `created_by_idx` (`created_by`);

--
-- Indexes for table `project_charter`
--
ALTER TABLE `project_charter`
  ADD PRIMARY KEY (`project_charter_id`);

--
-- Indexes for table `project_charter_stakeholder`
--
ALTER TABLE `project_charter_stakeholder`
  ADD PRIMARY KEY (`stakeholder_id`,`project_charter_id`);

--
-- Indexes for table `project_mp`
--
ALTER TABLE `project_mp`
  ADD PRIMARY KEY (`project_mp_id`);

--
-- Indexes for table `project_user`
--
ALTER TABLE `project_user`
  ADD KEY `project` (`project_id`),
  ADD KEY `user` (`user_id`);

--
-- Indexes for table `quality_mp`
--
ALTER TABLE `quality_mp`
  ADD PRIMARY KEY (`quality_mp_id`);

--
-- Indexes for table `requirements_mp`
--
ALTER TABLE `requirements_mp`
  ADD PRIMARY KEY (`requirements_mp_id`);

--
-- Indexes for table `risk_mp`
--
ALTER TABLE `risk_mp`
  ADD PRIMARY KEY (`risk_mp_id`);

--
-- Indexes for table `schedule_mp`
--
ALTER TABLE `schedule_mp`
  ADD PRIMARY KEY (`schedule_mp_id`);

--
-- Indexes for table `scope_mp`
--
ALTER TABLE `scope_mp`
  ADD PRIMARY KEY (`scope_mp_id`);

--
-- Indexes for table `stakeholder_mp`
--
ALTER TABLE `stakeholder_mp`
  ADD PRIMARY KEY (`stakeholder_mp_id`);

--
-- Indexes for table `stakeholder_register`
--
ALTER TABLE `stakeholder_register`
  ADD PRIMARY KEY (`stakeholder_id`);

--
-- Indexes for table `user`
--
ALTER TABLE `user`
  ADD PRIMARY KEY (`user_id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `communication_mp`
--
ALTER TABLE `communication_mp`
  MODIFY `communication_id` int(11) NOT NULL AUTO_INCREMENT;

ALTER TABLE `user`
  MODIFY `user_id` int(11) NOT NULL AUTO_INCREMENT;

ALTER TABLE `project`
  MODIFY `project_id` int(11) NOT NULL AUTO_INCREMENT;

--
-- AUTO_INCREMENT for table `cost_mp`
--
ALTER TABLE `cost_mp`
  MODIFY `cost_mp_id` int(11) NOT NULL AUTO_INCREMENT;

--
-- AUTO_INCREMENT for table `human_resources_mp`
--
ALTER TABLE `human_resources_mp`
  MODIFY `human_resources_mp_id` int(11) NOT NULL AUTO_INCREMENT;

--
-- AUTO_INCREMENT for table `procurement_mp`
--
ALTER TABLE `procurement_mp`
  MODIFY `procurement_mp_id` int(11) NOT NULL AUTO_INCREMENT;

--
-- AUTO_INCREMENT for table `project_charter`
--
ALTER TABLE `project_charter`
  MODIFY `project_charter_id` int(11) NOT NULL AUTO_INCREMENT;

--
-- AUTO_INCREMENT for table `project_mp`
--
ALTER TABLE `project_mp`
  MODIFY `project_mp_id` int(11) NOT NULL AUTO_INCREMENT;

--
-- AUTO_INCREMENT for table `quality_mp`
--
ALTER TABLE `quality_mp`
  MODIFY `quality_mp_id` int(11) NOT NULL AUTO_INCREMENT;

--
-- AUTO_INCREMENT for table `requirements_mp`
--
ALTER TABLE `requirements_mp`
  MODIFY `requirements_mp_id` int(11) NOT NULL AUTO_INCREMENT;

--
-- AUTO_INCREMENT for table `risk_mp`
--
ALTER TABLE `risk_mp`
  MODIFY `risk_mp_id` int(11) NOT NULL AUTO_INCREMENT;

--
-- AUTO_INCREMENT for table `schedule_mp`
--
ALTER TABLE `schedule_mp`
  MODIFY `schedule_mp_id` int(11) NOT NULL AUTO_INCREMENT;

--
-- AUTO_INCREMENT for table `scope_mp`
--
ALTER TABLE `scope_mp`
  MODIFY `scope_mp_id` int(11) NOT NULL AUTO_INCREMENT;

--
-- AUTO_INCREMENT for table `stakeholder_mp`
--
ALTER TABLE `stakeholder_mp`
  MODIFY `stakeholder_mp_id` int(11) NOT NULL AUTO_INCREMENT;

--
-- AUTO_INCREMENT for table `stakeholder_register`
--
ALTER TABLE `stakeholder_register`
  MODIFY `stakeholder_id` int(11) NOT NULL AUTO_INCREMENT;

--
-- Constraints for dumped tables
--

--
-- Limitadores para a tabela `project`
--
ALTER TABLE `project`
  ADD CONSTRAINT `created_by` FOREIGN KEY (`created_by`) REFERENCES `user` (`user_id`) ON DELETE NO ACTION ON UPDATE NO ACTION;

--
-- Limitadores para a tabela `project_user`
--
ALTER TABLE `project_user`
  ADD CONSTRAINT `project` FOREIGN KEY (`project_id`) REFERENCES `project` (`project_id`) ON DELETE CASCADE,
  ADD CONSTRAINT `user` FOREIGN KEY (`user_id`) REFERENCES `user` (`user_id`) ON DELETE CASCADE;
COMMIT;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;